export const routePaths = {
  login: '/login',
  dashboard: '/dashboard',
  regionManagers: '/region-managers',
  regions: '/regions',
  regionDetail: (id: number | string) => `/regions/${id}`,
  companies: '/companies',
  companyDetail: (id: number | string) => `/companies/${id}`,
  categories: '/categories',
  categoryDetail: (id: number | string) => `/categories/${id}`,
  services: '/services',
  serviceDetail: (id: number | string) => `/services/${id}`,
  skills: '/skills',
  profile: '/profile',
  forbidden: '/403',
  notFound: '/404',
} as const
