// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxKq-0r2cwFPLFoApxN5IldDvoCBjj1K0',
    appId: '1:572222321773:web:cefe58731591e3b66e7b64',
    messagingSenderId: '572222321773',
    projectId: 'cleanlink-54d24',
    authDomain: 'cleanlink-54d24.firebaseapp.com',
    storageBucket: 'cleanlink-54d24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB47vP5Nyw5k9a9HZkTiuHlAuXjLh4kISw',
    appId: '1:572222321773:android:ce7b3681986abcfb6e7b64',
    messagingSenderId: '572222321773',
    projectId: 'cleanlink-54d24',
    storageBucket: 'cleanlink-54d24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpqCz4KCZ700O4JExDtM8pcnE_B4VRYog',
    appId: '1:572222321773:ios:c22896df0323357d6e7b64',
    messagingSenderId: '572222321773',
    projectId: 'cleanlink-54d24',
    storageBucket: 'cleanlink-54d24.firebasestorage.app',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpqCz4KCZ700O4JExDtM8pcnE_B4VRYog',
    appId: '1:572222321773:ios:c22896df0323357d6e7b64',
    messagingSenderId: '572222321773',
    projectId: 'cleanlink-54d24',
    storageBucket: 'cleanlink-54d24.firebasestorage.app',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxKq-0r2cwFPLFoApxN5IldDvoCBjj1K0',
    appId: '1:572222321773:web:a4a43aaff77427cf6e7b64',
    messagingSenderId: '572222321773',
    projectId: 'cleanlink-54d24',
    authDomain: 'cleanlink-54d24.firebaseapp.com',
    storageBucket: 'cleanlink-54d24.firebasestorage.app',
  );
}
